FROM openjdk:21-jdk

LABEL "org.opencontainers.image.authors"="deepakraj11"

COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]